services: 
  terraria-server:
    build:
      context: https://github.com/OmegaSad/terraria-server-docker.git#test-branch
      args:
        - VERSION=latest
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true     
    ports:
      - 7778:7777
    volumes:
      - $WorldsFolder:/root/.local/share/Terraria/Worlds    
    environment:
      - world=/root/.local/share/Terraria/Worlds/world1.wld
      - autocreate=2
      - difficulty=2
      - password=hello
      - motd="Welcome to my server! :)"
